services:
  - type: web
    name: toxicity-prediction-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python test.py
    envVars:
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0